name: Publish bot to production
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: Deploy to Cloudflare Workers with Wrangler
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: publish --name discordbot
          secrets: |
            DISCORD_TOKEN
            DISCORD_APPLICATION_ID
            DISCORD_TEST_GUILD_ID
            DISCORD_PUBLIC_KEY
            FIRESTORE_PRIVATE_KEY
            FIRESTORE_SERVICE_ACCOUNT
            CLOUDFLARE_API_TOKEN
        env:
          DISCORD_TOKEN: ${{secrets.DISCORD_TOKEN}}
          DISCORD_APPLICATION_ID: ${{secrets.DISCORD_APPLICATION_ID}}
          DISCORD_TEST_GUILD_ID: ${{secrets.DISCORD_TEST_GUILD_ID}}
          DISCORD_PUBLIC_KEY: ${{secrets.DISCORD_PUBLIC_KEY}}
          FIRESTORE_PRIVATE_KEY: ${{secrets.FIRESTORE_PRIVATE_KEY}}
          FIRESTORE_SERVICE_ACCOUNT: ${{secrets.FIRESTORE_SERVICE_ACCOUNT}}
          CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_TOKEN}}